### ISSUE TITLE
Bug: scheduler gets unhandled exception and dies on "(ab){2,5}"

### ISSUE THREAD

**Issue by noahgibbs** [kddnewton/regular_expression#68]
In the benchmarking code I try to compile the expression "(ab){2,5}" with the X86 compiler. The scheduler code dies with an unhandled exception:

~~~
noah@Noahs-MacBook-Pro-3 regular_expression % rake benchmark
cd /Users/noah/src/github.com/kddnewton/regular_expression
Traceback (most recent call last):
	7: from ./bench/run_benchmarks.rb:106:in `<main>'
	6: from ./bench/run_benchmarks.rb:106:in `each'
	5: from ./bench/run_benchmarks.rb:109:in `block in <main>'
	4: from ./bench/run_benchmarks.rb:109:in `map'
	3: from ./bench/run_benchmarks.rb:110:in `block (2 levels) in <main>'
	2: from ./bench/run_benchmarks.rb:37:in `time_all_matches'
	1: from /Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/pattern.rb:14:in `compile'
/Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/scheduler.rb:96:in `schedule': unhandled exception
~~~

The code there just says the scheduler is broken:

~~~
        else
          # The scheduler is broken.
          raise
        end
~~~

**Comment by kddnewton** [comment]
@noahgibbs This should now be fixed on `main`

**Comment by noahgibbs** [comment]
This issue isn't fixed for me. After merging latest main, I can run benchmark *without* this regexp. But if I include this one, I get the following error:

~~~
noah@Noahs-MacBook-Pro-3 regular_expression % bundle exec rake benchmark
cd /Users/noah/src/github.com/kddnewton/regular_expression
[warning(regexp)] scheduling failed with 18 blocks, 10 scheduled, 7 remaining, 0 ready, 0 deferred - using fallback scheduler to recover
[warning(regexp)] scheduling failed with 18 blocks, 10 scheduled, 7 remaining, 0 ready, 0 deferred - using fallback scheduler to recover
Traceback (most recent call last):
	8: from ./bench/run_benchmarks.rb:110:in `<main>'
	7: from ./bench/run_benchmarks.rb:110:in `each'
	6: from ./bench/run_benchmarks.rb:113:in `block in <main>'
	5: from ./bench/run_benchmarks.rb:113:in `map'
	4: from ./bench/run_benchmarks.rb:114:in `block (2 levels) in <main>'
	3: from ./bench/run_benchmarks.rb:39:in `time_all_matches'
	2: from /Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/pattern.rb:17:in `compile'
	1: from /Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/compiler/ruby.rb:14:in `to_proc'
/Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/compiler/ruby.rb:14:in `eval': (eval):10: syntax error, unexpected local variable or method, expecting `when' (SyntaxError)
        flag = string_n < string.size && ...
        ^~~~
(eval):19: syntax error, unexpected `when', expecting `end'
      when :fail
      ^~~~
(eval):22: syntax error, unexpected `when', expecting `end'
      when :state_2180_0
      ^~~~
(eval):63: syntax error, unexpected `when', expecting `end'
      when :state_2260_0
      ^~~~
(eval):65: syntax error, unexpected `when', expecting `end'
      when :state_2280_0
      ^~~~
(eval):76: syntax error, unexpected `when', expecting `end'
      when :state_2240_1
      ^~~~
(eval):80: syntax error, unexpected `when', expecting `end'
      when :state_2260_0
      ^~~~
(eval):82: syntax error, unexpected `when', expecting `end'
      when :state_2300_0
      ^~~~
(eval):103: syntax error, unexpected `when', expecting `end'
      when :state_2300_1
      ^~~~
(eval):107: syntax error, unexpected `when', expecting `end'
      when :state_2300_0
      ^~~~
(eval):117: syntax error, unexpected `when', expecting `end'
      when :state_2340_0
      ^~~~
(eval):131: syntax error, unexpected `when', expecting `end'
      when :state_2340_0
      ^~~~
(eval):141: syntax error, unexpected `when', expecting `end'
      when :state_2140_0
      ^~~~
(eval):152: syntax error, unexpected `end', expecting '}'
    end
    ^~~
~~~

**Comment by kddnewton** [comment]
Ahh sorry Noah! I'll look at this

**Comment by kddnewton** [comment]
This will fix it: https://github.com/kddnewton/regular_expression/pull/73

**Comment by noahgibbs** [comment]
Cool. Yup, that fixes it.
